apiVersion: v1
kind: Namespace
metadata:
  name: vulnerable
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vuln-app
  namespace: vulnerable
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vuln-app
  template:
    metadata:
      labels:
        app: vuln-app
    spec:
      containers:
      - name: app
        image: nginxinc/nginx-unprivileged:alpine
        ports:
        - containerPort: 8080
        securityContext:
          allowPrivilegeEscalation: true
          runAsUser: 0
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: overprivileged-sa
  namespace: vulnerable
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vuln-app-admin
subjects:
- kind: ServiceAccount
  name: overprivileged-sa
  namespace: vulnerable
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io